# Generated by Django 4.0.4 on 2022-05-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_url', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('u_created', models.DateTimeField(auto_now_add=True)),
                ('u_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
