# Generated by Django 4.0.4 on 2022-05-23 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centraal', '0002_url_u_trello_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='u_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_urls', to=settings.AUTH_USER_MODEL),
        ),
    ]
